import type { Metadata } from "next";
import { DM_Sans, Geist, Geist_Mono, Inter, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/shared/widgets";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MyPay",
  description: "Generated by create next app",
  
};

export const inter = Inter({
  variable:'--font--inter',
  subsets:['latin'],

})

export const getPlusjakarta = Plus_Jakarta_Sans({
  variable:'--font-plus_jakartasans',
  subsets:['latin'],
  weight:["200","300","400","500",'600','700','800']
})

export const dm_sans = DM_Sans({
  variable:'--font-plus_jakartasans',
  subsets:['latin'],
  weight:["200","300","400","500",'600','700','800']
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

<head>
  <title>My Pay</title>
  <link rel="icon" href="/logo.svg" type="image/svg+xml" />
</head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${getPlusjakarta} ${dm_sans} ${inter.variable} antialiased  bg-[#00020D]`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
